.TH sxwm 1 sxwm\-VERSION
.SH NAME
sxwm \- simple/scriptable X window manager
.SH SYNOPSIS
.B sxwm
.RB [ \-v ]
.SH DESCRIPTION
sxwm is a simple/scriptable window manager for X. 
By default, it doesn't do much, aside from focusing newly opened windows and handling the mouse. Instead, all window manipulation duties are delegated to sxutils, a collection of small command line tools, and scripts which can be tied to keybindings with the help of programs such as sxhkd or xbindkeys. 
